### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by MarquiseRosier** [barbua/FSA#1]
I was wondering if we can possibly put an instruction file to direct people on how to build the application in Windows or Linux and use the code? 

I successfully built the application in a Linux Environment and generated a pyd Dynamic Library file. I am certain I can change the CMakeLists.txt file and generate a .so file instead and load the functions offered by the PyFSA code into a driver program and run examples. I fixed some problems with the code in order to get this working build. I look forward to collaborating with you on this project a little more. Please message me any features you would like to add to the project or any updates you would like me to make!

**Comment by barbua** [comment]
Hi Marquise

Thank you for offering to help with this.
Sure, it would be great if you could write a readme file with instructions
the way you think it's appropriate.
Also, if you could change the CMakeLists.txt to detect Linux/Windows and
set the right extension for the library automatically it would be great.
Maybe you could also change the code to make it compile without problems in
both Windows and Linux.
I can' think of any other features right now. Do you have any ideas?

Adrian

**Comment by MarquiseRosier** [comment]
Dear Adrian, 

I do have a few ideas! I want to incorporate Unit Testing in the various classes and maybe refactor the structure so that building is easier. Perhaps separating classes and their function implementations into 
the following folders

include ###Will store header files purely for method prototypes and class declarations
src ###will store actual implementation code
tests ###I want to implement GoogleTest to ensure functionality is fail proof
bin ###I want to put all the results of a build into a designated bin folder
.dep ###I want this folder to be our dependencies like GoogleTest, CPPCheck, other tools. 

es I can modify the CMakeLists.txt and ensure it can build on both major operating systems. I plan to start submitting Issues for these things so that we can remember them and tackle them one by one!

**Comment by MarquiseRosier** [comment]
Also please do not worry about all the issues I am making. They are all mostly quick fixes, I simply want some kind of accountability and issue tracking on my part!

**Comment by barbua** [comment]
Sounds great!
