### ISSUE TITLE
Py_InitModule deprecated

### ISSUE THREAD

**Issue by MarquiseRosier** [barbua/FSA#12]
Python2.7 supports the bits of code that invoke Py_InitModule, however, if our users have Python3.x they will not have this support any longer. I have configured the CMakeFile to successfully generate everything in Windows and Linux and generate depending on the users operating system; however, this issue means we have to prepare code for both cases. This would entail two versions of the code in PyFSA.cpp that run depending on some Macro being set if Python is Python2.x OR Python3.x

(void) Py_InitModule("libPyFSA", _Methods);

Can be found in PyFSA.cpp

**Comment by barbua** [comment]
Isn't there another init module that works for both versions?

**Comment by MarquiseRosier** [comment]
I am searching but please send me information on it if you find it! 
I also found that PyIntObject is no longer offered in Python3. 

It has been replaced by PyLongObject so some of the code is going to change!

I found a MacroVariable that ships with Python called PY_VERSION_HEX which gives us a Hexadecimal number that allows us to check version numbers. We can simply define variables for the versions based on whether this Hex is less than 0x300000 or greater than which would give us the ability to give the compiler code based on what version of python we are running

**Comment by barbua** [comment]
One of my former students told me about SWIG. We could use that instead to interface FSA with Python.

**Comment by MarquiseRosier** [comment]
I would definitely like to do that if it makes it easier. We are having link issues in Visual Studio but that shouldn't be too hard to fix especially if we decide to change how we're interfacing Python & C++

**Comment by MarquiseRosier** [comment]
I hear good things about CTypes as well apparently CTypes allows you to interface Python and C++ in a way that works irrespective of Python version differences.

**Comment by barbua** [comment]
Sounds great!

**Comment by MarquiseRosier** [comment]
This has been solved. Modern Module Initialization methods have been used and the old initialization algorithm has been preserved by checking for Python versions and adjusting code accordingly.
