### ISSUE TITLE
DataMemory Throwing Errors

### ISSUE THREAD

**Issue by MarquiseRosier** [barbua/FSA#13]
I am working on a little bug I found. 

DataMemory is a templated class that depends on DataSource, it inherits a function called KeepOnly(std::vector<int>&, bool) 

If you look in the KeepOnly implementation it calls another KeepOnly() function and passes two vectors. There is no KeepOnly function declared that takes two vectors!

Also the compiler gets mad because a conversion must take place, where these functions are expecting an integer, they receive floats instead, I am attempting to fix this right now.

I was wondering as well, what you would say to zipping this code and shipping it to users with python already included? If they have windows? This would make it a lot easier versus forcing them to download python and then searching for it.

**Comment by MarquiseRosier** [comment]
I have also fixed the CmakeList to work on Linux and Windows, would you want me to make a pull request or i can finish fixing everything and submit it in one lump sum.

**Comment by MarquiseRosier** [comment]
I am also linking my project to AppVeyor you should link the master to it too! This provides automated building of our application upon committing code to ensure our program still builds with every commit! It also gives us the ability to test our code on someone elses computer and not just our two's!

You would just go to AppVeyor.com, sign up and link it to PyFSA

**Comment by barbua** [comment]
Ok, connected to AppVeyor.

**Comment by MarquiseRosier** [comment]
This has been fixed.
