### ISSUE TITLE
CMAKELIST NEEDS TO BE FIXED FOR LINUX

### ISSUE THREAD

**Issue by MarquiseRosier** [barbua/FSA#14]
This is an issue simply to make it known that Linux Building will not work yet! The next Commit will correct the CMakeList.

**Comment by MarquiseRosier** [comment]
Hey Dr. Barbu, I am working on our project sorry about not making the deadline, I have been hard at work though and will finish soon. 

There is a problem that 64 bit Windows machines and 64 bit Linux machines have. 

Some people have multiple versions of python installed, our code can find all of them, but it is very random with which version our code links to. Our code picks either the 32 bit or 64 bit python to include in our project. 

A problem with the user is that if the CMake script picks 32 bit python, and the user has Visual Studio that wants to generate a 64 bit .pyd, an error will be thrown saying we cannot link to 32 bit dynamic libraries to generate a 64 bit dynamic library. 

I have to determine what version of python is used depending on what version of Visual Studios the user has. 

Now I can do this, but there is another dilemna, the version i pick might not be the version that the Cmake script picks. The Cmake script picks whichever Python version is configured to run when someone types (python) into the command prompt. This is bad because if someone downloads numpy they will install it using the command (python setup.py install) which uses the python version the Cmake script might pick but that might not be the correct one to generate the correct dynamic library. So they might install Numpy in the wrong place. 

I can actually download Numpy and install it into the correct python version through our Cmake Script but I don't know what you think about this. Leaving it up to the user will probably make for a confusing installation process!

**Comment by barbua** [comment]
Assume that there is only one version. People with multiple versions can
fix it themselves.
Don't worry about the 32/64 bit either. Assume it will work well.
