### ISSUE TITLE
PutIntoVector Called Without Being in Source Files

### ISSUE THREAD

**Issue by MarquiseRosier** [barbua/FSA#2]
In DataMemory.h file, PutIntoVector(arg1, arg2, arg3) is called two times wrongly, Files containing its implementation and declaration are ScsUtil.cpp/ScsUtil.h Either provide an implementation or simply uncomment and including the files in the next Pull Request.

template<class Tp,class TpY>
bool DataMemory<Tp,TpY>::ReadSvmX(const char *name, const char *dlm, bool append){
        char line[100000];
        std::vector<std::string> v,v2;
        FILE *f=fopen(name,"rt");
        if (f==0)
                return false;
        if (!append){
                _x.clear();
                _y.clear();
                this->_nVar=0;
        }
        while(!feof(f)){
                std::vector<Tp> tmp;
                tmp.reserve(1000);
                tmp.assign(this->_nVar,0);
                if (fgets(line, 100000, f)==0)
                        break;
                **PutIntoVector(v, line,dlm);**
                for (int i=0;i<(int)v.size();i++){
                        **PutIntoVector(v2, v[i].c_str(),":");**
                        int idx=atoi(v2[0].c_str());
                        Tp val=(Tp)atof(v2[1].c_str());
                        while (idx>=tmp.size())
                                tmp.push_back(0);
                        tmp[idx]=val;
                }
                this->_nVar=std::max((int)tmp.size(),this->_nVar);
                _x.push_back(tmp);
        }
        fclose(f);
        return true;
}

**Comment by barbua** [comment]
We don't need any reading/writing ability for Datamemory, so let's just remove the whole function ReadSvmX.

**Comment by MarquiseRosier** [comment]
Got it! I submitted the changes via a pull request waiting on your approval and I will start constructing the test cases for your code!
