### ISSUE TITLE
VapnikLoss<template>::Value function invocation

### ISSUE THREAD

**Issue by MarquiseRosier** [barbua/FSA#8]
In LossFunctions.h 
VapnikLoss has function named Value with signature 
static float Value(std::vector<float> &x, int y)

The code makes no changes to the inputs so Value(const std::vector<float> &x) is best to ensure no changes to container can contaminate sensitive data.

Additionally, 
Much of the functions in LossFunctions.h use template arguments

template<class LossFunction, class Tp, class TpY>
float SumLoss(std::vector<Tp> &c, std::vector<TpY> &y){

However, they do things like set Tp sum = 0, which assumes Tp is a numerical type 
they also do things like call VapnikLoss<LossFunction>::Value( args,...,args) with templated std::vectors despite the fact that the Vapnik::Value function will have to cast the templated call to float. 

Solution:

Change all instances of float to double as float has significant precision loss in big calculations.
Change template functions that assume numerical templates to just functions taking const references to 
doubles, as templates on that scale causes slower run time
Make Static functions Inline
Use size_type of container instead of casting to int for iterating containers
remove casting of template types to int, this can make code fail proof!

**Comment by barbua** [comment]
Ok, but the data will usually be float, and so will be the vector x.
Making the data double with increase its size in the memory and then we'll only be able to handle smaller datasets.

**Comment by MarquiseRosier** [comment]
This is very true! My fear was that you might lose some accuracy in running calculations on the data like derivatives and multiplications. I was also afraid that using float puts an upper bound on how many degrees of significance our data can be when entered. However, I might be exaggerating the importance of this detail it doesn't seem like you'll be running calculations on decimal numbers with more than 7 degrees of significance.

**Comment by barbua** [comment]
It's fine for the value and derivative to be double, but the input x should either be float or templated.

**Comment by MarquiseRosier** [comment]
Got it!
