### ISSUE TITLE
DataSource Cheapen inlines

### ISSUE THREAD

**Issue by MarquiseRosier** [barbua/FSA#9]
it is cheaper to return bools! 
The conditional expressions in DataSource return bools 
and are then converted into ints to fit the return types, making them bool
returns saves space and time!

**Comment by barbua** [comment]
Can you be more precise of the function you are referring to? DataSource.h has no conditional expressions.

**Comment by MarquiseRosier** [comment]
inline int GetYLine(std::vector<float> &x, int kStar){
	float sum=0;
	for (int m=0;m<kStar;m++)
		sum+=x[m*10]; // line
	**return (sum<0);
}**

inline int GetYLine(std::vector<float> &x, std::vector<float> &beta){
	float sum=0;
	int kStar=(int)beta.size();
	for (int m=0;m<kStar;m++)
		sum+=x[m*10]*beta[m]; // line
	**return (sum<0);**
}

inline int GetYLineNoFeatSlc(std::vector<float> &x, int kStar){
	float sum=0;
	for (int m=0;m<kStar;m++)
		sum+=x[m]; // line
	**return (sum<0);**
}

inline int GetYSphere(std::vector<float> &x, int kStar){
	float sum=0;
	for (int m=0;m<kStar;m++)
		sum+=pow(abs(x[m*10]),2.f); // sphere
	**return (sum<kStar);**
}

inline int GetYRing(std::vector<float> &x, int kStar){
	float sum=0;
	for (int m=0;m<kStar;m++)
		sum+=pow(abs(x[m*10]),2.f); // ring
	**return (sum<kStar&&sum>=0.5f*kStar);**
}

inline int GetYStar(std::vector<float> &x, int kStar){
	float sum=0;
	for (int m=0;m<kStar;m++)
		sum+=pow(abs(x[m*10]),0.4f); // star
	**return (sum<0.85*kStar);**
}
Ahh sorry about that the above functions return boolean conditionals but stuff them into int return types 

These functions return ints that are made from casting conditionals which generate bools which is essentially using more memory for a smaller type!

**Comment by MarquiseRosier** [comment]
The return statements are conditionals like 
return (sum < 0.85*kstar)
return (sum < kstar && sum >= 0.5f*kStar)

etc etc

**Comment by barbua** [comment]
Optimizing everything like this makes the code very rigid and adapted to a particular purpose.
This is research code, not targeted to be the fastest possible.
Leave these the way they are. Most likely we don't even use them. 
Maybe we should just erase them altogether.

**Comment by MarquiseRosier** [comment]
Ok. I am sorry I definitely have an optimize everything approach to these things. You're right! Do you think we should erase them away we might need the functionality later!

**Comment by barbua** [comment]
Erase them. This kind of data generation should be done outside of DataSource anyway.

**Comment by MarquiseRosier** [comment]
Ok Got it!
